name: ✨ 機能リクエスト
description: 新しい機能やアイデアを提案する
title: "[機能リクエスト]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        機能リクエストありがとうございます！
        新しいアイデアや改善提案を歓迎します。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題
      description: どのような課題や問題を解決したいですか？
      placeholder: 現在、XXXをする際にYYYという問題があります
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能や改善を提案しますか？
      placeholder: ZZZという機能を追加することで、この問題を解決できると思います
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に検討した解決策があれば記載してください
      placeholder: 他の方法として、AAAやBBBも検討しました

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: この機能の重要度はどの程度ですか？
      options:
        - 低（あれば便利）
        - 中（業務効率が向上する）
        - 高（現在の業務に支障がある）
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: その他
      description: モックアップ、参考リンクなど、追加情報があれば記載してください
